# Generated by Django 2.1.1 on 2018-12-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181216_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categort',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': '文章列表', 'verbose_name_plural': '文章列表'},
        ),
        migrations.AddField(
            model_name='posts',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
