# Generated by Django 2.1.1 on 2018-12-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181218_2003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
