# Generated by Django 2.1.1 on 2018-12-22 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181222_1652'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categort',
            new_name='Category',
        ),
    ]
